<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>395f7d3b-1c78-443a-b0d4-78fba1bbe9fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GovUk.Frontend.AspNetCore" Version="3.4.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

</Project>
