<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="GovUk.Frontend.AspNetCore" Version="3.4.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.10" />
  </ItemGroup>
</Project>